#ifndef W_CONFIG_HPP_WAF
#define W_CONFIG_HPP_WAF

#define HAVE_IS_DEFAULT_CONSTRUCTIBLE 1
#define HAVE_IS_MOVE_CONSTRUCTIBLE 1
#define HAVE_CXX_OVERRIDE 1
#define HAVE_LIBRT
#define HAVE_LIBRESOLV
/*#undef HAVE_UNIX_SOCKETS*/
#define DEFAULT_CONFIG_FILE "./nfd.conf"
#define HAVE_CUSTOM_LOGGER 1

#endif /* W_CONFIG_HPP_WAF */
